package:
  name: mpsplots
  version: {{ GIT_DESCRIBE_TAG | replace("v", "") }}

source:
  git_url: https://github.com/MartinPdeS/MPSPlots.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools >=40.8.0
    - setuptools-scm >=8.0
    - wheel

  run:
    - python >=3.10
    - matplotlib >=3,<4
    - pyvista >=0.45.3

test:
  imports:
    - MPSPlots

  requires:
    - python >=3.10
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ~=1.5.0
    - coverage ~=7.6.1

about:
  home: https://github.com/MartinPdeS/MPSPlots
  license: MIT
  license_file: LICENSE
  summary: A matplotlib wrapper for deferred plots.
  description: |
    MPSPlots is a matplotlib wrapper that allows deferred plot creation.
    This is useful when creating plots in loops or functions where the actual
    rendering of the plot is not desired immediately.
  dev_url: https://github.com/MartinPdeS/MPSPlots
  doc_url: https://mpsplots.readthedocs.io
  keywords:
    - matplotlib
    - plotting
    - visualization

extra:
  recipe-maintainers:
    - MartinPdeS