name: Ubuntu-Workflow


permissions:
    contents: write

on:
    workflow_call:
        inputs:
            python_version_list:
                type: string
                required: false
                default: "['3.10']"


jobs:
    job_create_wheel:
        name: "Python ${{ matrix.python_version }}"
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.10'









# -
