name: Ubuntu-Workflow


permissions:
    contents: write

on:
    workflow_call:
        inputs:
            python_version_list:
                type: string
                required: false
                default: "['3.10']"


jobs:
    job_create_wheel:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        matrix:
            python_version: ${{ fromJson(inputs.python_version_list) }}

        steps:
          - name: "Checkout repository"
            uses: actions/checkout@v3
            with:
                submodules: 'true'

          - uses: MartinPdeS/MPSActions/interpret_python_version@master
            with:
                python_version: ${{ matrix.python_version }}

            uses: actions/setup-python@v4
            with:
                python-version: env.PYTHON_DOTTED_VERSION

          - name: "Run: Tests"
            run: |
                python -m pip install --upgrade pip
                python -m pip install -e .[development]
                pytest -s
                python setup.py bdist_wheel


          - name: "Upload: Wheel"
            uses: actions/upload-artifact@v3
            with:
                name: "manylinux_wheel_python${{ env.PYTHON_CP_VERSION }}"
                path: ./dist/*










# -
