name: Ubuntu-Workflow


permissions:
    contents: write

on:
    workflow_call:
        inputs:
            python_version_list:
                type: string
                required: false
                default: "['3.10']"


jobs:
    job_create_wheel:
        name: "Python ${{ matrix.python_version }}"
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.10'



        # strategy:
        #     fail-fast: false
        #     matrix:
        #         python_version: ${{ fromJson(inputs.python_version_list) }}

        # steps:
        #   - uses: actions/checkout@v3
        #     with:
        #         submodules: 'true'

        #   - uses: MartinPdeS/MPSActions/interpret_python_version@master
        #     with:
        #         python_version: ${{ matrix.python_version }}

        #   - uses: actions/setup-python@v4
        #     with:
        #         python-version: ${{ env.dotted_python_version }}

        #   - name: "Run: Tests"
        #     run: |
        #         python -m pip install --upgrade pip
        #         python -m pip install -e .[development]
        #         pytest -s
        #         python setup.py bdist_wheel

        #   - name: "Upload: Wheel"
        #     uses: actions/upload-artifact@v3
        #     with:
        #         name: "manylinux_wheel_python${{ env.PYTHON_CP_VERSION }}"
        #         path: ./dist/*










# -
