# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: "master"
  push:
    branches: "master"

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - name: "Set-up: Python ${{ env.cp_python_version }}"
        uses: actions/setup-python@v4
        id: cp310
        with:
            python-version: "3.10"

      - name: "Install: Dependencies for headless server"
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install libgl1-mesa-glx xvfb

      - name: "Chekcout requirements and files for testing"
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              tests
              requirements

      - name: Install everything, run the tests, produce the .coverage file
        run: |
          python build --wheel
          python -m pip install .[testing]
          pytest --cov=${{ inputs.package-name }} --cov-report=html

      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}