name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    build_pure_python:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.10'

    job_post_coverage:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Ubuntu_x86_64]
        uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_coverage_badge.yml@master
        secrets: inherit
        with:
            python_version: "3.10"

    job_build_documentation:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Ubuntu_x86_64]
        uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_documentation.yml@master
        secrets: inherit
        with:
            python_version: "3.10" #no documentation for python 3.7 (pickle5 not presentË˜)

    job_publish_wheel:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Ubuntu_x86_64, job_build_documentation, job_post_coverage]
        uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_pypi.yml@master
        secrets: inherit
        with:
            python_version: "3.10"
