name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  Ubuntu_x86_64:
    uses: MartinPdeS/MPSPlots/.github/workflows/build_ubuntu_x86_64.yml@main
    secrets: inherit
    with:
      python_version: "[['3.10', 'cp310']]"

  job_post_coverage:
    needs: [Ubuntu_x86_64]
    uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_coverage_badge.yml@main
    secrets: inherit
    with:
      python_version: "3.10"

  job_build_documentation:
    needs: [Ubuntu_x86_64]
    uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_documentation.yml@main
    secrets: inherit
    with:
      python_version: "3.10" #no documentation for python 3.7 (pickle5 not presentË˜)

  job_publish_wheel:
    needs: [Ubuntu_x86_64]
    uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_pypi.yml@main
    secrets: inherit
    with:
      python_version: "3.10"
