name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    build_pure_python:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.10'

    job_post_coverage:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [build_pure_python]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/compute_unittest_coverage@master
            with:
                python-version: "3.10"
                auth: ${{ secrets.MPdS_gist_token }}
                gistID: c4f12a9ab97461a9453d9a174ae88e17

    job_build_documentation:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [build_pure_python]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_documentation@master
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              package-name: MPSPlots
              python-version: "3.10" #no documentation for python 3.7 (pickle5 not presentË˜)

    job_publish_wheel:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [build_pure_python, job_build_documentation, job_post_coverage]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
              python-version: "3.10"
              password: ${{ secrets.PYPI_API_TOKEN }}
