name: Deploy

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: write

jobs:
    Ubuntu_x86_64:
        uses: MartinPdeS/MPSPlots/.github/workflows/build_ubuntu_x86_64.yml@main
        secrets: inherit
        with:
            python_version_list: "['3.10']"

    job_post_coverage:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Ubuntu_x86_64]
        uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_coverage_badge.yml@main
        secrets: inherit
        with:
            python_version: "3.10"

    job_build_documentation:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Ubuntu_x86_64]
        uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_documentation.yml@main
        secrets: inherit
        with:
            python_version: "3.10" #no documentation for python 3.7 (pickle5 not presentË˜)

    job_publish_wheel:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [Ubuntu_x86_64, job_build_documentation, job_post_coverage]
        uses: MartinPdeS/MPSPlots/.github/workflows/sub_deploy_pypi.yml@main
        secrets: inherit
        with:
            python_version: "3.10"
