name: documentation_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true
        default: "3.10"

jobs:
  deploy_badge:
    name: "Publish documentation to RTD"
    runs-on: ubuntu-latest
    steps:
      - uses: MartinPdeS/MPSActions/publish_documentation@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          package_name: MPSPlots