name: badge_deploy

# https://github.com/YannickJadoul/Parselmouth/blob/master/.github/workflows/wheels.yml
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: true
        default: "3.10"

jobs:
  deploy_badge:
    runs-on: ubuntu-latest
    steps:
      - uses: MartinPdeS/MPSActions/compute_unittest_coverage@master
        with:
          auth: ${{ secrets.MPdS_gist_token }}
          gistID: c4f12a9ab97461a9453d9a174ae88e17
